version: '3.4'
services:
  racing-app-node:
      build: ./node
      ports:
        - "49160:8080"
      links:
        - "racing-app-db"
      depends_on: 
        racing-app-db:
          condition: service_healthy
          
      container_name: services-racing-node-app
      networks:
        - services

  racing-app-db:
    build: ./mysql
    ports:
      - "3307:3306"
    container_name: services-racing-mysql-app
    command: --default-authentication-plugin=mysql_native_password
    networks:
        - services
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  services: